# Generated by Django 4.0.3 on 2022-04-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullNameCustomer', models.CharField(max_length=255)),
                ('cnicCustomer', models.CharField(max_length=13)),
                ('addressCustomer', models.CharField(max_length=255)),
                ('cityCustomer', models.CharField(max_length=25)),
                ('dobCustomer', models.DateField()),
                ('ReviewCustomer', models.TextField(max_length=10000)),
            ],
        ),
    ]
