# Generated by Django 4.0.3 on 2022-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.CharField(max_length=30)),
                ('bookingSlot', models.CharField(max_length=30)),
                ('serviceType', models.CharField(max_length=30)),
                ('ServiceProviderID', models.CharField(max_length=30)),
            ],
        ),
    ]
